///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TaskModelDataNotComplated {
/*
{
  "id": 47,
  "title": "ulaaa",
  "description": "nasılsın",
  "isComplete": false,
  "createdAt": "2022-04-04T20:50:42.000Z"
} 
*/

  int? id;
  String? title;
  String? description;
  bool? isComplete;
  String? createdAt;

  TaskModelDataNotComplated({
    this.id,
    this.title,
    this.description,
    this.isComplete,
    this.createdAt,
  });
  TaskModelDataNotComplated.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    description = json['description']?.toString();
    isComplete = json['isComplete'];
    createdAt = json['createdAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['description'] = description;
    data['isComplete'] = isComplete;
    data['createdAt'] = createdAt;
    return data;
  }
}

class TaskModelData {
/*
{
  "notComplated": [
    {
      "id": 47,
      "title": "ulaaa",
      "description": "nasılsın",
      "isComplete": false,
      "createdAt": "2022-04-04T20:50:42.000Z"
    }
  ]
} 
*/

  List<TaskModelDataNotComplated?>? notComplated;

  TaskModelData({
    this.notComplated,
  });
  TaskModelData.fromJson(Map<String, dynamic> json) {
  if (json['notComplated'] != null) {
  final v = json['notComplated'];
  final arr0 = <TaskModelDataNotComplated>[];
  v.forEach((v) {
  arr0.add(TaskModelDataNotComplated.fromJson(v));
  });
    notComplated = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (notComplated != null) {
      final v = notComplated;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['notComplated'] = arr0;
    }
    return data;
  }
}

class TaskModel {
/*
{
  "message": "Notlar başarıyla getirildi",
  "status": true,
  "data": {
    "notComplated": [
      {
        "id": 47,
        "title": "ulaaa",
        "description": "nasılsın",
        "isComplete": false,
        "createdAt": "2022-04-04T20:50:42.000Z"
      }
    ]
  }
} 
*/

  String? message;
  bool? status;
  TaskModelData? data;

  TaskModel({
    this.message,
    this.status,
    this.data,
  });
  TaskModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    status = json['status'];
    data = (json['data'] != null) ? TaskModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
